### ISSUE TITLE
文字列をDCで確保した時に、文字列の末尾に`\0`が無い

### ISSUE THREAD

**Issue by Hiroya-W** [omzn/casljs#4]
## 現象

https://github.com/omzn/casljs/blob/a2bc6ab6ce9cd817728d4b70bdb53ab8ba8b53f0/casl2/test_WRITESTR.cas#L89-L90

のように、連続して文字列を確保した時に、`\0`が無いので、文字列の区切りが分からない

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/43127622/178191344-780833f5-558e-4d40-8830-be4033db0a7c.png">

## 解決方法

`0000`のデータを文字列の末尾に対応する場所に書き込む

**Comment by Hiroya-W** [comment]
`0061` から `Hello, CASL2`が書き込まれ、`006D` に `0000` がありますが、これが `\0` に対応しています。
次の `006E` から `No loading strings` が続きます。

![image](https://user-images.githubusercontent.com/43127622/178192373-144dcf2f-f6b9-433c-a259-956746b4d7a1.png)

**Comment by Hiroya-W** [comment]
perl版では、`\0` は無いようです。

```
(*'-') < ./comet2 sample11.csl.com
This is COMET II, version 1.1.0 (11 Sep 2008).
Copyright (c) 2001-2008, Osamu Mizuno.
All rights reserved.
Reading object from sample11.csl.com...done.

PR  #0000 [ PUSH     #0000, GR1      ]
SP  #ff00(  -256)  FR  001  (     1)
GR0 #0000(     0)  GR1 #0000(     0)  GR2 #0000(     0)  GR3 #0000(     0)
GR4 #0000(     0)  GR5 #0000(     0)  GR6 #0000(     0)  GR7 #0000(     0)
comet> d
Delete all breakpoints? (y or n) n
comet> h
List of commands:

r,  run         Start execution of program.
s,  step        Step execution.  Argument N means do this N times.
b,  break       Set a breakpoint at specified address.
d,  delete      Delete some breakpoints.
i,  info        Print information on breakpoints.
p,  print       Print status of PC/FR/SP/GR0..GR7 registers.
du, dump        Dump 128 words of memory image from specified address.
st, stack       Dump 128 words of stack image.
f,  file        Use FILE as program to be debugged.
j,  jump        Continue program at specifed address.
m,  memory      Change the memory at ADDRESS to VALUE.
di, disasm      Disassemble 32 words from specified address.
h,  help        Print list of commands.
q,  quit        Exit comet.
comet> du
0000: 7001 0000 7002 0000 1210 0026 1220 0025 .....& %
0008: f000 fff2 7120 7110 7001 0000 7002 0000 .. .....
0010: 1210 0046 1220 0045 f000 fff0 7120 7110 .F E.. .
0018: 7001 0000 7002 0000 1210 0046 1220 0045 .....F E
0020: f000 fff2 7120 7110 8100 000d 0048 0065 .. ...He
0028: 006c 006c 006f 002c 0020 0043 0041 0053 llo, CAS
0030: 004c 0032 002e 004e 006f 0020 006c 006f L2.No lo
0038: 0061 0064 0069 006e 0067 0020 0073 0074 ading st
0040: 0072 0069 006e 0067 0073 0000 0000 0000 rings...
0048: 0000 0000 0000 0000 0000 0000 0000 0000 ........
0050: 0000 0000 0000 0000 0000 0000 0000 0000 ........
0058: 0000 0000 0000 0000 0000 0000 0000 0000 ........
0060: 0000 0000 0000 0000 0000 0000 0000 0000 ........
0068: 0000 0000 0000 0000 0000 0000 0000 0000 ........
0070: 0000 0000 0000 0000 0000 0000 0000 0000 ........
0078: 0000 0000 0000 0000 0000 0000 0000 0000 ........
comet>
```

**Comment by Hiroya-W** [comment]
これはバグなんでしょうか...？

**Comment by omzn** [comment]
<img width="676" alt=" 2022-07-11 at 14 41 27" src="https://user-images.githubusercontent.com/1021773/178196760-10dedc98-1c8e-4fb4-b542-181f36f88946.png">
元のCASL IIの仕様には，文字列の後ろに0を入れるとは書いてありません．末尾が0であるのはC言語の都合です．
そもそも，CASL IIではOUT命令で必ず文字数を指定するので，末尾を知る必要はありません．前のシミュレータでは，OBUFSIZEを0にすると，勝手に0までの文字列を表示する拡張か何かがあったのですかね？？ (その拡張がどこにも明示されていないのですが…)

**Comment by Hiroya-W** [comment]
いくらかは、負担を軽減するためにと講義の資料で、アセンブリ言語で書かれた文字列出力のプログラムが提供されていました。
例えば、WRITESTR がその1つです。
https://github.com/omzn/casljs/blob/a2bc6ab6ce9cd817728d4b70bdb53ab8ba8b53f0/casl2/test_WRITESTR.cas#L12-L88

この WRITESTRは、事前に文字列の先頭アドレスを GR1に入れた後、CALL WRITESTRすることで、文字列の長さをカウントしたあと、それを OBUFSIZE に入れて、OUT OBUF, OBUFSIZE を呼び出しています

この文字列の長さをカウントする時に、\0までカウントを繰り返すをしているので、この仕様を利用しているみたいです

CASL IIの文字列の仕様では特に言及されていないということが分かったので、

> 便利にするためのサブルーチンのために言語仕様が改変されてるのだね．

ということのようです
