### ISSUE TITLE
動作確認一覧

### ISSUE THREAD

**Issue by Hiroya-W** [omzn/casljs#7]
## N個の数の入力を受け取って合計を求める
- [x] sample11
- [x] sample11p
- [x] sample11pp
  - 2N個受け取る

## 何もしない
- [x] sample12

## 平方根を求める
- [x] sample13

## 電卓

- [x] sample14
- [x] sample14p

## Nに対して2n, n**2, n**3, 2**nを求める

- [x] sample15
  - ~~`Uncaught RangeError: Maximum call stack size exceeded terminal_casl2comet2.js:1337`~~
- [x] sample15a
  - ~~`Uncaught RangeError: Maximum call stack size exceeded terminal_casl2comet2.js:1337`~~

## エラトステネスの篩

- [x] sample16
  - ~~CASL IIアセンブルで無限ループする？~~ 解決 #9 
  - ~~`Uncaught RangeError: Maximum call stack size exceeded`~~ 解決 #10

## GCM, LCMを計算する

- [x] sample17

## 素因数分解

- [x] sample18
  - ~~`Uncaught RangeError: Maximum call stack size exceeded terminal_casl2comet2.js:1389`~~

## 電卓改（割り算が正確に表現できる）

- [x] sample19p
- [x] sample29p

## 代入

- [x] sample21
  - int
- [x] sample22
  - bool
- [x] sample23
  - char

## `It's OK?`を出力する

- [x] sample24

## 入力された文字が`a`かそうでないか

- [x] sample25

## キャスト

`'a' == 97`, `'B' == 66`

- [x] sample25t

## 1~Nまでの合計を求める

- [x] sample26

## whileのネストがあるプログラム

動作内容は特に意味は無さそう？

- [x] sample27

## procedureの呼び出し

- [x] sample28p

## 紙幣と硬貨の数をカウントする

- [x] sample2a
  - 動いているけど、出力が違う。~~僕が用意したやつが間違っています~~ そもそも、与えられた sample2a.mplがやりたいことを実現できていないプログラムなようで、実行は正しいということが分かりました。
  - sample2a.mpl はバグっていますが、バグっているとおりに動いているのでヨシとします。

## グローバル変数、ローカル変数、仮引数で同じ変数名があっても正しくなっているか

- [x] sample31p
  - 1と3を入力するのが正解
- [x] sample33p
  - 1回目の入力は関係無い。2回目は1。

## 入力した文字を指定した回数出力する(readln, readを使った方法)

- [x] sample34
  - ~~文字が出力されない？僕が用意したやつが間違っています~~
  - 合ってた。入力の与え方が違っていただけっぽかった。

```
// 1回目
3
a
// 2回目
9b
```

## 文字、記号を全部出力する

- [x] sample35
  - ~~`Uncaught RangeError: Maximum call stack size exceeded`~~

**Comment by omzn** [comment]
* sample16はassembleに異常に時間がかかる(30秒ぐらい) さらにスタックもあふれる．
* `Uncaught RangeError: Maximum call stack size exceeded` に対する修正をしたつもりだったけど，まだ直っていない．setTimeout()しても本質的な解決ではないみたいなので，どうするか…再帰をやめるのが一番なのだけど，exec_in()を非再帰関数から利用する方法を思いつかない．
